[package]
name = "redstone_schem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hematite-nbt = { git = "https://github.com/PistonDevelopers/hematite_nbt" }
serde = "1"
